# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github_issues_encoder.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github_issues_encoder.proto',
  package='github_issues_encoder',
  syntax='proto3',
  serialized_options=b'\252\002\020GithubGRPCServer',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bgithub_issues_encoder.proto\x12\x15github_issues_encoder\"\x15\n\x05Issue\x12\x0c\n\x04text\x18\x01 \x01(\t\"9\n\x0c\x45ncodedIssue\x12\x11\n\tinput_ids\x18\x01 \x03(\x03\x12\x16\n\x0e\x61ttention_mask\x18\x02 \x03(\x03\x32X\n\x07\x45ncoder\x12M\n\x06\x45ncode\x12\x1c.github_issues_encoder.Issue\x1a#.github_issues_encoder.EncodedIssue\"\x00\x42\x13\xaa\x02\x10GithubGRPCServerb\x06proto3'
)




_ISSUE = _descriptor.Descriptor(
  name='Issue',
  full_name='github_issues_encoder.Issue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='github_issues_encoder.Issue.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=75,
)


_ENCODEDISSUE = _descriptor.Descriptor(
  name='EncodedIssue',
  full_name='github_issues_encoder.EncodedIssue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_ids', full_name='github_issues_encoder.EncodedIssue.input_ids', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attention_mask', full_name='github_issues_encoder.EncodedIssue.attention_mask', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['Issue'] = _ISSUE
DESCRIPTOR.message_types_by_name['EncodedIssue'] = _ENCODEDISSUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Issue = _reflection.GeneratedProtocolMessageType('Issue', (_message.Message,), {
  'DESCRIPTOR' : _ISSUE,
  '__module__' : 'github_issues_encoder_pb2'
  # @@protoc_insertion_point(class_scope:github_issues_encoder.Issue)
  })
_sym_db.RegisterMessage(Issue)

EncodedIssue = _reflection.GeneratedProtocolMessageType('EncodedIssue', (_message.Message,), {
  'DESCRIPTOR' : _ENCODEDISSUE,
  '__module__' : 'github_issues_encoder_pb2'
  # @@protoc_insertion_point(class_scope:github_issues_encoder.EncodedIssue)
  })
_sym_db.RegisterMessage(EncodedIssue)


DESCRIPTOR._options = None

_ENCODER = _descriptor.ServiceDescriptor(
  name='Encoder',
  full_name='github_issues_encoder.Encoder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=136,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='Encode',
    full_name='github_issues_encoder.Encoder.Encode',
    index=0,
    containing_service=None,
    input_type=_ISSUE,
    output_type=_ENCODEDISSUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENCODER)

DESCRIPTOR.services_by_name['Encoder'] = _ENCODER

# @@protoc_insertion_point(module_scope)
