# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import github_issues_encoder_pb2 as github__issues__encoder__pb2


class EncoderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encode = channel.unary_unary(
                '/github_issues_encoder.Encoder/Encode',
                request_serializer=github__issues__encoder__pb2.Issue.SerializeToString,
                response_deserializer=github__issues__encoder__pb2.EncodedIssue.FromString,
                )


class EncoderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Encode(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encode': grpc.unary_unary_rpc_method_handler(
                    servicer.Encode,
                    request_deserializer=github__issues__encoder__pb2.Issue.FromString,
                    response_serializer=github__issues__encoder__pb2.EncodedIssue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'github_issues_encoder.Encoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Encoder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github_issues_encoder.Encoder/Encode',
            github__issues__encoder__pb2.Issue.SerializeToString,
            github__issues__encoder__pb2.EncodedIssue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
